services:
  postgres:
    image: postgres:latest
    container_name: postgreSQL
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8081:5432"
    networks:
      - postgres_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 1s
      timeout: 1s
      retries: 10

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: data_aggregator
    ports:
      - "${API_PORT}:8080"
    networks:
      - postgres_network
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge