services:
  postgres:
    image: postgres:latest
    container_name: postgreSQL
    environment:
      POSTGRES_DB: subscriptions
      POSTGRES_USER: qwert
      POSTGRES_PASSWORD: 12345
    ports:
      - "8081:5432"
    networks:
      - postgres_network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgAdminDB
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "9090:80"
    networks:
      - postgres_network
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

networks:
  postgres_network:
    driver: bridge