basePath: /
definitions:
  dto.CostSummaryReqDTO:
    properties:
      end_period:
        type: string
      service_name:
        type: string
      start_period:
        type: string
      user_id:
        type: string
    type: object
  dto.CostSummaryRespDTO:
    properties:
      query_param:
        $ref: '#/definitions/dto.CostSummaryReqDTO'
      total_cost:
        type: integer
    type: object
  dto.MessageDTO:
    properties:
      message:
        type: string
      time:
        type: string
    type: object
  dto.SubRecordDTO:
    properties:
      end_date:
        type: string
      price:
        type: integer
      service_name:
        type: string
      start_date:
        type: string
      user_id:
        type: string
    type: object
  dto.SubRecordWithIdDTO:
    properties:
      id:
        type: integer
      subRecord:
        $ref: '#/definitions/dto.SubRecordDTO'
    type: object
  dto.UpdateSubRecordDTO:
    properties:
      end_date:
        type: string
      price:
        type: integer
      service_name:
        type: string
      start_date:
        type: string
      user_id:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: dima.drozdov15@mail.ru
  description: REST-cервис для агрегации данных об онлайн-подписках пользователей
  title: Aгрегатор данных
  version: "1.0"
paths:
  /subscriptions:
    get:
      description: Получает все записи об подписках
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SubRecordWithIdDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.MessageDTO'
      summary: Лист всех записей
      tags:
      - subscriptions
    post:
      consumes:
      - application/json
      description: Создает новую запись о подписке пользователя
      parameters:
      - description: Данные о подписке
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/dto.SubRecordDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.SubRecordWithIdDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.MessageDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.MessageDTO'
      summary: Создание новой записи
      tags:
      - subscriptions
  /subscriptions/{id}:
    delete:
      description: Удаление записи о подписке по ID
      parameters:
      - description: ID записи
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.MessageDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.MessageDTO'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.MessageDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.MessageDTO'
      summary: Удаление записи о подписке
      tags:
      - subscriptions
    get:
      description: Получает запись о подписке по ее ID
      parameters:
      - description: ID записи
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SubRecordWithIdDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.MessageDTO'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.MessageDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.MessageDTO'
      summary: Запись по ID
      tags:
      - subscriptions
    put:
      consumes:
      - application/json
      description: Изменение данных о подписке в записе
      parameters:
      - description: ID записи
        in: path
        name: id
        required: true
        type: integer
      - description: Данные для обновление записи
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateSubRecordDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SubRecordWithIdDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.MessageDTO'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.MessageDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.MessageDTO'
      summary: Изменение записи
      tags:
      - subscriptions
  /subscriptions/cost:
    get:
      description: Подсчет суммарной стоимости всех подписок за выбранный период и
        опциональными фильтрами
      parameters:
      - description: Фильтр User ID
        in: query
        name: user_id
        type: string
      - description: Фильтр названия подписки
        in: query
        name: service_name
        type: string
      - description: Начальная дата (YYYY-MM-DD)
        format: string
        in: query
        name: start_period
        required: true
        type: string
      - description: Конечная дата (YYYY-MM-DD)
        format: string
        in: query
        name: end_period
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CostSummaryRespDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.MessageDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.MessageDTO'
      summary: Подсчет суммарной стоимости подписок
      tags:
      - subscriptions
swagger: "2.0"
